dataset:
  auto_delete_dataset_folder: false
  num_rows_to_create_in_new_csv_files: None
  path_chest_imagenome: Data/chest-imagenome
  path_full_dataset: Model/report-generation-model/data/datasets
  path_mimic_cxr: Data/mimic-cxr
  path_mimic_cxr_jpg: Data/mimic-cxr-jpg
evaluation:
  batch_size: 32
  bertscore_similarity_threshold: 0.9
  image_input_size: 512
  max_num_tokens_generate: 300
  name_of_best_full_model_checkpoint: checkpoint_val_loss_12.564_overall_steps_13940.pt
  num_batches_of_generated_reports_to_save_to_file: 5
  num_batches_of_generated_sentences_to_save_to_file: 5
  num_beams: 4
  num_workers: 10
  path_test_set_evaluation_scores_txt_files: Model/report-generation-model/evaluation/scores
  path_to_best_object_detector_weights: Model/report-generation-model/runs/object_detector/run_10/weights/val_loss_15.017_epoch_8.pth
  run: 12
  seed: 41
generation:
  bertscore_similarity_threshold: 0.9
  generated_reports_folder_path: Model/report-generation-model/generation/reports
  image_folder_paths: Model/report-generation-model/generation/images
  image_format: .jpg
  image_input_size: 512
  max_num_tokens_generate: 300
  mean: 0.471
  num_beams: 4
  path_to_best_full_model_weights: Model/report-generation-model/runs/full_model/run_12/checkpoints/checkpoint_val_loss_12.564_overall_steps_13940.pt
  path_to_best_object_detector_weights: Model/report-generation-model/runs/object_detector/run_10/weights/val_loss_15.017_epoch_8.pth
  std: 0.302
logger:
  txt_file_for_logging: log_file_dataset_creation.txt
model:
  path_chexbert_weights: Model/report-generation-model/models/CheXbert/chexbert.pth
runs:
  auto_delete_run_folder: false
  path_runs_full_model: Model/report-generation-model/runs/full_model
  path_runs_object_detector: Model/report-generation-model/runs/object_detector
train:
  classification_modules:
    batch_size: 16
    bertscore_similarity_threshold: 0.9
    cooldown_lr_scheduler: 5
    effective_batch_size: 16
    epochs: 10
    evaluate_every_k_batches: 200
    factor_lr_scheduler: 0.5
    image_input_size: 512
    lr: 5e-5
    max_num_tokens_generate: 200
    num_batches_of_generated_reports_to_save_to_file: 5
    num_batches_of_generated_sentences_to_save_to_file: 5
    num_batches_to_process_for_language_model_evaluation: 5
    num_beams: 4
    num_images_to_plot: 8
    num_workers: 10
    path_to_best_classification_modules_weights: None
    path_to_best_object_detector_weights: Model/report-generation-model/runs/object_detector/run_10/weights/val_loss_15.017_epoch_8.pth
    patience_lr_scheduler: 5
    percentage_of_train_set_to_use: 1.0
    percentage_of_val_set_to_use: 0.05
    pretrain_without_lm_model: true
    run: 11
    seed: 41
    threshold_lr_scheduler: 1e-3
    weight_binary_classifier_region_abnormal_loss: 5
    weight_binary_classifier_region_selection_loss: 5
    weight_language_model_loss: 2
    weight_object_detector_loss: 1
  full_model:
    batch_size: 1
    bertscore_similarity_threshold: 0.9
    cooldown_lr_scheduler: 5
    effective_batch_size: 16
    epochs: 5
    evaluate_every_k_batches: 5000
    factor_lr_scheduler: 0.5
    image_input_size: 512
    lr: 5e-5
    max_num_tokens_generate: 300
    num_batches_of_generated_reports_to_save_to_file: 4
    num_batches_of_generated_sentences_to_save_to_file: 4
    num_batches_to_process_for_language_model_evaluation: 4
    num_beams: 4
    num_images_to_plot: 8
    num_workers: 10
    path_to_best_classification_modules_weights: Model/report-generation-model/runs/full_model/run_11/checkpoints/checkpoint_val_loss_105.191_overall_steps_1314.pt
    path_to_best_object_detector_weights: Model/report-generation-model/runs/object_detector/run_10/weights/val_loss_15.017_epoch_8.pth
    patience_lr_scheduler: 3
    percentage_of_train_set_to_use: 1.0
    percentage_of_val_set_to_use: 0.05
    pretrain_without_lm_model: false
    run: 12
    seed: 41
    threshold_lr_scheduler: 1e-3
    weight_binary_classifier_region_abnormal_loss: 5
    weight_binary_classifier_region_selection_loss: 5
    weight_language_model_loss: 2
    weight_object_detector_loss: 1
  object_detector:
    batch_size: 16
    cooldown_lr_scheduler: 5
    effective_batch_size: 16
    epochs: 10
    evaluate_every_k_steps: 200
    factor_lr_scheduler: 0.5
    image_input_size: 512
    lr: 1e-3
    num_workers: 10
    patience_lr_scheduler: 5
    percentage_of_train_set_to_use: 1.0
    percentage_of_val_set_to_use: 0.2
    run: 10
    seed: 41
    threshold_lr_scheduler: 1e-3
