mimic_cxr:
  name: "mimic_cxr"
  data_type: "imagetext"
  data_path: "Model/image-classification-model/datasets/mimic-cxr-jpg/mimic_valid.csv"
  image_size: ${base.image_size}
  text_max_length: ${base.text_max_length}
